/**
 * vmf/vmf4_inputtoresult.java
 *
 * This file was generated by MapForce 2016r2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.mapforce.vmf;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import com.altova.text.tablelike.*;
import com.altova.text.*;
import com.altova.text.edi.*;
import java.util.*;

public class vmf4_inputtoresult extends com.altova.TraceProvider 
{

	
	static class Main implements IEnumerable
	{
		java.lang.String var1_input;
	
		public Main(java.lang.String var1_input)
		{
			this.var1_input = var1_input;
		}

		public IEnumerator enumerator() {return new MFEmptySequence().enumerator();}
				
	}





	public static IEnumerable create(java.lang.String var1_input)
	{
		if (hash == null) init();
		Object o = hash.get(var1_input);
		if (o != null)
			return new MFSingletonSequence(o);
		else
			return new MFEmptySequence();

	}
	
	private static java.util.HashMap hash = null;

	private synchronized static void init()
	{
		hash = new java.util.HashMap();
		hash.put(com.altova.CoreTypes.box("Add Heat Recovery"), com.altova.CoreTypes.box("21000"));
		hash.put(com.altova.CoreTypes.box("Boiler decentralization"), com.altova.CoreTypes.box("22000"));
		hash.put(com.altova.CoreTypes.box("Boiler Room Insulation"), com.altova.CoreTypes.box("23000"));
		hash.put(com.altova.CoreTypes.box("Convert Gas-Fired Unit to Boiler Loop"), com.altova.CoreTypes.box("24000"));
		hash.put(com.altova.CoreTypes.box("Heating - Cleaning and Repair"), com.altova.CoreTypes.box("25000"));
		hash.put(com.altova.CoreTypes.box("Heating - Operating Protocols, Calibration, and/or Sequencing"), com.altova.CoreTypes.box("26000"));
		hash.put(com.altova.CoreTypes.box("Replace Boiler or Furnace"), com.altova.CoreTypes.box("27000"));
		hash.put(com.altova.CoreTypes.box("Replace Burner"), com.altova.CoreTypes.box("28000"));
		hash.put(com.altova.CoreTypes.box("Chiller plant pumping, piping, and controls retrofits and replacements"), com.altova.CoreTypes.box("29000"));
		hash.put(com.altova.CoreTypes.box("Install VSD on Electric Centrifugal Chillers"), com.altova.CoreTypes.box("30000"));
		hash.put(com.altova.CoreTypes.box("Replace Chiller"), com.altova.CoreTypes.box("31000"));
		hash.put(com.altova.CoreTypes.box("Add or Upgrade BAS/EMS/EMCS"), com.altova.CoreTypes.box("32000"));
		hash.put(com.altova.CoreTypes.box("Add or Upgrade Controls"), com.altova.CoreTypes.box("33000"));
		hash.put(com.altova.CoreTypes.box("Controls - Uncategorized"), com.altova.CoreTypes.box("34000"));
		hash.put(com.altova.CoreTypes.box("Cooling - Operating Protocols, Calibration, and/or Sequencing "), com.altova.CoreTypes.box("35000"));
		hash.put(com.altova.CoreTypes.box("Distribution - Operating Protocols, Calibration, and/or Sequencing"), com.altova.CoreTypes.box("36000"));
		hash.put(com.altova.CoreTypes.box("Domestic Hot Water - Operating Protocols, Calibration, and/or Sequencing"), com.altova.CoreTypes.box("37000"));
		hash.put(com.altova.CoreTypes.box("Motors - Add Drive Controls"), com.altova.CoreTypes.box("38000"));
		hash.put(com.altova.CoreTypes.box("Pneumatic to DDC Convert"), com.altova.CoreTypes.box("39000"));
		hash.put(com.altova.CoreTypes.box("Process/Plug Equipment - Operating Protocols, Calibration, and/or Sequencing"), com.altova.CoreTypes.box("40000"));
		hash.put(com.altova.CoreTypes.box("System - Operating Protocols, Calibration, and/or Sequencing "), com.altova.CoreTypes.box("41000"));
		hash.put(com.altova.CoreTypes.box("Ventilation - Operating Protocols, Calibration, and/or Sequencing "), com.altova.CoreTypes.box("42000"));
		hash.put(com.altova.CoreTypes.box("Add Duct Insulation"), com.altova.CoreTypes.box("43000"));
		hash.put(com.altova.CoreTypes.box("Add or replace Cooling Tower"), com.altova.CoreTypes.box("44000"));
		hash.put(com.altova.CoreTypes.box("Convert CV System to VAV System"), com.altova.CoreTypes.box("45000"));
		hash.put(com.altova.CoreTypes.box("Cooling - Heat Recovery"), com.altova.CoreTypes.box("46000"));
		hash.put(com.altova.CoreTypes.box("Cooling - Uncategorized"), com.altova.CoreTypes.box("47000"));
		hash.put(com.altova.CoreTypes.box("Distribution - Balancing"), com.altova.CoreTypes.box("48000"));
		hash.put(com.altova.CoreTypes.box("Distribution - Improve Fans"), com.altova.CoreTypes.box("49000"));
		hash.put(com.altova.CoreTypes.box("Duct Insulation"), com.altova.CoreTypes.box("50000"));
		hash.put(com.altova.CoreTypes.box("Duct Sealing"), com.altova.CoreTypes.box("51000"));
		hash.put(com.altova.CoreTypes.box("Economizer Cycle"), com.altova.CoreTypes.box("52000"));
		hash.put(com.altova.CoreTypes.box("HVAC - Distribution - Uncategorized"), com.altova.CoreTypes.box("53000"));
		hash.put(com.altova.CoreTypes.box("HVAC - System - Cleaning and/or Repair "), com.altova.CoreTypes.box("54000"));
		hash.put(com.altova.CoreTypes.box("HVAC - System - Training and/or Documentation"), com.altova.CoreTypes.box("55000"));
		hash.put(com.altova.CoreTypes.box("HVAC damper and controller repair or replacement"), com.altova.CoreTypes.box("56000"));
		hash.put(com.altova.CoreTypes.box("Repair Leaks / Seal Ducts"), com.altova.CoreTypes.box("57000"));
		hash.put(com.altova.CoreTypes.box("Replace Package Units"), com.altova.CoreTypes.box("58000"));
		hash.put(com.altova.CoreTypes.box("Replace Packaged Terminal Units"), com.altova.CoreTypes.box("59000"));
		hash.put(com.altova.CoreTypes.box("Replace/Modify AHU"), com.altova.CoreTypes.box("60000"));
		hash.put(com.altova.CoreTypes.box("Ventilation - Balancing"), com.altova.CoreTypes.box("61000"));
		hash.put(com.altova.CoreTypes.box("Ventilation - Cleaning and Repair"), com.altova.CoreTypes.box("62000"));
		hash.put(com.altova.CoreTypes.box("Ventilation - Uncategorized"), com.altova.CoreTypes.box("63000"));
		hash.put(com.altova.CoreTypes.box("Ventilation - Upgrade Fans"), com.altova.CoreTypes.box("64000"));
		hash.put(com.altova.CoreTypes.box("Add daylight dimming"), com.altova.CoreTypes.box("65000"));
		hash.put(com.altova.CoreTypes.box("Add occupancy sensors"), com.altova.CoreTypes.box("66000"));
		hash.put(com.altova.CoreTypes.box("Fiber optic lighting technologies"), com.altova.CoreTypes.box("67000"));
		hash.put(com.altova.CoreTypes.box("Light Emitting Diode technologies"), com.altova.CoreTypes.box("68000"));
		hash.put(com.altova.CoreTypes.box("Lighting - Cleaning and/or Repair"), com.altova.CoreTypes.box("69000"));
		hash.put(com.altova.CoreTypes.box("Lighting - Operation Protocols, Calibration, and/or Sequencing"), com.altova.CoreTypes.box("70000"));
		hash.put(com.altova.CoreTypes.box("Retrofit with CFLs"), com.altova.CoreTypes.box("71000"));
		hash.put(com.altova.CoreTypes.box("Retrofit with T-5"), com.altova.CoreTypes.box("72000"));
		hash.put(com.altova.CoreTypes.box("Retrofit with T-8"), com.altova.CoreTypes.box("73000"));
		hash.put(com.altova.CoreTypes.box("Retrofit/Replace"), com.altova.CoreTypes.box("74000"));
		hash.put(com.altova.CoreTypes.box("Spectrally enhanced lighting"), com.altova.CoreTypes.box("75000"));
		hash.put(com.altova.CoreTypes.box("Add Attic/Knee Wall Insulation"), com.altova.CoreTypes.box("76000"));
		hash.put(com.altova.CoreTypes.box("Add Shading Devices"), com.altova.CoreTypes.box("77000"));
		hash.put(com.altova.CoreTypes.box("Add Window Films"), com.altova.CoreTypes.box("78000"));
		hash.put(com.altova.CoreTypes.box("Air Sealing"), com.altova.CoreTypes.box("79000"));
		hash.put(com.altova.CoreTypes.box("Cool/Green Roof Installed"), com.altova.CoreTypes.box("80000"));
		hash.put(com.altova.CoreTypes.box("Envelope - Cleaning and/or Repair"), com.altova.CoreTypes.box("81000"));
		hash.put(com.altova.CoreTypes.box("Increase Ceiling Insulation"), com.altova.CoreTypes.box("82000"));
		hash.put(com.altova.CoreTypes.box("Increase Floor Insulation"), com.altova.CoreTypes.box("83000"));
		hash.put(com.altova.CoreTypes.box("Increase Roof Insulation"), com.altova.CoreTypes.box("84000"));
		hash.put(com.altova.CoreTypes.box("Increase Wall Insulation"), com.altova.CoreTypes.box("85000"));
		hash.put(com.altova.CoreTypes.box("Insulate Attic Hatch / Stair Box"), com.altova.CoreTypes.box("86000"));
		hash.put(com.altova.CoreTypes.box("Insulate Foundation"), com.altova.CoreTypes.box("87000"));
		hash.put(com.altova.CoreTypes.box("Insulate Thermal Bypass"), com.altova.CoreTypes.box("88000"));
		hash.put(com.altova.CoreTypes.box("Insulation or Replacement of Solar Screens"), com.altova.CoreTypes.box("89000"));
		hash.put(com.altova.CoreTypes.box("Replace Glazing"), com.altova.CoreTypes.box("90000"));
		hash.put(com.altova.CoreTypes.box("Window replacement"), com.altova.CoreTypes.box("91000"));
		hash.put(com.altova.CoreTypes.box("Add Recirculating Pumps"), com.altova.CoreTypes.box("92000"));
		hash.put(com.altova.CoreTypes.box("Convert System from Steam to hot Water"), com.altova.CoreTypes.box("93000"));
		hash.put(com.altova.CoreTypes.box("Distribution - Add Pipe Insulation"), com.altova.CoreTypes.box("94000"));
		hash.put(com.altova.CoreTypes.box("Domestic Hot Water - Add Pipe Insulation"), com.altova.CoreTypes.box("95000"));
		hash.put(com.altova.CoreTypes.box("Domestic Hot Water - Heat Recovery"), com.altova.CoreTypes.box("96000"));
		hash.put(com.altova.CoreTypes.box("Domestic Hot Water - Replace or Upgrade Heater"), com.altova.CoreTypes.box("97000"));
		hash.put(com.altova.CoreTypes.box("Install Low-Flow Fixtures"), com.altova.CoreTypes.box("98000"));
		hash.put(com.altova.CoreTypes.box("Repair or replacement of existing condensate return systems and installation of new condensate return systems"), com.altova.CoreTypes.box("99000"));
		hash.put(com.altova.CoreTypes.box("Separate DHW from Heating"), com.altova.CoreTypes.box("100000"));
		hash.put(com.altova.CoreTypes.box("Solar Hot Water"), com.altova.CoreTypes.box("101000"));
		hash.put(com.altova.CoreTypes.box("Steam trap repair and replacement"), com.altova.CoreTypes.box("102000"));
		hash.put(com.altova.CoreTypes.box("Motors - Replace with higher efficiency"), com.altova.CoreTypes.box("103000"));
		hash.put(com.altova.CoreTypes.box("Motors - Replace with VSD"), com.altova.CoreTypes.box("104000"));
		hash.put(com.altova.CoreTypes.box("Replacement of ice/refrigeration equipment with high efficiency units"), com.altova.CoreTypes.box("105000"));
		hash.put(com.altova.CoreTypes.box("CHP/Cogeneration systems installation"), com.altova.CoreTypes.box("106000"));
		hash.put(com.altova.CoreTypes.box("Fuel cells installation"), com.altova.CoreTypes.box("107000"));
		hash.put(com.altova.CoreTypes.box("Microturbines installation"), com.altova.CoreTypes.box("108000"));
		hash.put(com.altova.CoreTypes.box("Landfill gas, wastewater treatment plant digester gas, and coalbed methane power plant installation"), com.altova.CoreTypes.box("109000"));
		hash.put(com.altova.CoreTypes.box("Passive solar heating installation"), com.altova.CoreTypes.box("110000"));
		hash.put(com.altova.CoreTypes.box("Photovoltaic system installation"), com.altova.CoreTypes.box("111000"));
		hash.put(com.altova.CoreTypes.box("Replacement of AC and heating units with ground coupled heat pump systems"), com.altova.CoreTypes.box("112000"));
		hash.put(com.altova.CoreTypes.box("Solar hot water system installation"), com.altova.CoreTypes.box("113000"));
		hash.put(com.altova.CoreTypes.box("Solar ventilation preheating system installation"), com.altova.CoreTypes.box("114000"));
		hash.put(com.altova.CoreTypes.box("Wind energy system installation"), com.altova.CoreTypes.box("115000"));
		hash.put(com.altova.CoreTypes.box("Wood waste, other organic waste stream heating or power plant installation"), com.altova.CoreTypes.box("116000"));
		hash.put(com.altova.CoreTypes.box("Gas distribution systems installation"), com.altova.CoreTypes.box("117000"));
		hash.put(com.altova.CoreTypes.box("Power factor correction"), com.altova.CoreTypes.box("118000"));
		hash.put(com.altova.CoreTypes.box("Power quality upgrades"), com.altova.CoreTypes.box("119000"));
		hash.put(com.altova.CoreTypes.box("Transformers installation"), com.altova.CoreTypes.box("120000"));
		hash.put(com.altova.CoreTypes.box("Low-flow faucets and showerheads"), com.altova.CoreTypes.box("121000"));
		hash.put(com.altova.CoreTypes.box("Low-flow plumbing equipment"), com.altova.CoreTypes.box("122000"));
		hash.put(com.altova.CoreTypes.box("On-site sewer treatment systems"), com.altova.CoreTypes.box("123000"));
		hash.put(com.altova.CoreTypes.box("Water efficient irrigation"), com.altova.CoreTypes.box("124000"));
		hash.put(com.altova.CoreTypes.box("Gas cooling"), com.altova.CoreTypes.box("125000"));
		hash.put(com.altova.CoreTypes.box("Thermal energy storage"), com.altova.CoreTypes.box("126000"));
		hash.put(com.altova.CoreTypes.box("Change to more favorable rate schedule"), com.altova.CoreTypes.box("127000"));
		hash.put(com.altova.CoreTypes.box("Energy service billing and meter auditing recommendations"), com.altova.CoreTypes.box("128000"));
		hash.put(com.altova.CoreTypes.box("Lower energy cost supplier(s) (where applicable)"), com.altova.CoreTypes.box("129000"));
		hash.put(com.altova.CoreTypes.box("Data Center - Uncategorized"), com.altova.CoreTypes.box("130000"));
		hash.put(com.altova.CoreTypes.box("Industrial process improvement"), com.altova.CoreTypes.box("131000"));
		hash.put(com.altova.CoreTypes.box("Production and/or manufacturing improvements"), com.altova.CoreTypes.box("132000"));
		hash.put(com.altova.CoreTypes.box("Recycling and other waste stream reductions"), com.altova.CoreTypes.box("133000"));
		hash.put(com.altova.CoreTypes.box("De-lamp vending machines"), com.altova.CoreTypes.box("134000"));
		hash.put(com.altova.CoreTypes.box("Plug timers"), com.altova.CoreTypes.box("135000"));
		hash.put(com.altova.CoreTypes.box("Process/Plug Equipment - Cleaning and/or Repair"), com.altova.CoreTypes.box("136000"));
		hash.put(com.altova.CoreTypes.box("Process/Plug Equipment - Replace with Energy Star Rated"), com.altova.CoreTypes.box("137000"));
		hash.put(com.altova.CoreTypes.box("Replace air-cooled ice/refrigeration equipment"), com.altova.CoreTypes.box("138000"));
		hash.put(com.altova.CoreTypes.box("Replace refrigerators"), com.altova.CoreTypes.box("139000"));
		hash.put(com.altova.CoreTypes.box("Addition or Annex"), com.altova.CoreTypes.box("140000"));
		hash.put(com.altova.CoreTypes.box("Cleaning and/or Repair - Uncategorized"), com.altova.CoreTypes.box("141000"));
		hash.put(com.altova.CoreTypes.box("Fuel Conversion"), com.altova.CoreTypes.box("142000"));
		hash.put(com.altova.CoreTypes.box("Training and/or Documentation - Uncategorized"), com.altova.CoreTypes.box("143000"));
		hash.put(com.altova.CoreTypes.box("Unknown"), com.altova.CoreTypes.box("144000"));
	}

	public static com.altova.mapforce.IEnumerable eval(java.lang.String var1_input) throws java.lang.Exception
	{

		return create(var1_input);
	
	}

}
