/**
 * Text_file2Document.java
 *
 * This file was generated by MapForce 2016r2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.mapforce.Text_file2;



import com.altova.text.tablelike.ColumnSpecification;
import com.altova.text.tablelike.Header;
import com.altova.text.tablelike.ISerializer;
import com.altova.text.tablelike.csv.Table;
import com.altova.text.tablelike.csv.Serializer;

public class Text_file2Document extends Table
{
	protected ISerializer createSerializer()
	{
		Serializer result= new Serializer(this,0);
		result.getFormat().setAssumeFirstRowAsHeaders(false);
		result.getFormat().setFieldDelimiter(',');
		
		result.getFormat().setQuoteCharacter('\"');
		
		result.getFormat().setRemoveEmpty(true);
		result.getFormat().setAlwaysQuote(0 == 1);
		return result;
	}
	protected void initHeader(Header header)
	{
		
		header.add(new ColumnSpecification("Label"));
		header.add(new ColumnSpecification("Number of Measures"));
	}
	public Text_file2Document(com.altova.typeinfo.TypeInfo tableType,int lineend) {
        super( tableType,lineend);
    }
}



