/**
 * vmf/vmf17_inputtoresult.java
 *
 * This file was generated by MapForce 2016r2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.mapforce.vmf;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import java.util.*;

public class vmf17_inputtoresult extends com.altova.TraceProvider 
{

	
	static class Main implements IEnumerable
	{
		java.lang.String var1_input;
	
		public Main(java.lang.String var1_input)
		{
			this.var1_input = var1_input;
		}

		public IEnumerator enumerator() {return new MFEmptySequence().enumerator();}
				
	}





	public static IEnumerable create(java.lang.String var1_input)
	{
		if (hash == null) init();
		Object o = hash.get(var1_input);
		if (o != null)
			return new MFSingletonSequence(o);
		else
			return new MFEmptySequence();

	}
	
	private static java.util.HashMap hash = null;

	private synchronized static void init()
	{
		hash = new java.util.HashMap();
		hash.put(com.altova.CoreTypes.box("<10"), com.altova.CoreTypes.box(new java.math.BigDecimal(".05")));
		hash.put(com.altova.CoreTypes.box("10"), com.altova.CoreTypes.box(new java.math.BigDecimal(".1")));
		hash.put(com.altova.CoreTypes.box("25"), com.altova.CoreTypes.box(new java.math.BigDecimal(".25")));
		hash.put(com.altova.CoreTypes.box("50"), com.altova.CoreTypes.box(new java.math.BigDecimal(".5")));
		hash.put(com.altova.CoreTypes.box("75"), com.altova.CoreTypes.box(new java.math.BigDecimal(".75")));
		hash.put(com.altova.CoreTypes.box("90"), com.altova.CoreTypes.box(new java.math.BigDecimal(".9")));
		hash.put(com.altova.CoreTypes.box("100"), com.altova.CoreTypes.box(new java.math.BigDecimal("1")));
	}

	public static com.altova.mapforce.IEnumerable eval(java.lang.String var1_input) throws java.lang.Exception
	{

		return create(var1_input);
	
	}

}
