/**
 * vmf/vmf49_inputtoresult.java
 *
 * This file was generated by MapForce 2016r2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.mapforce.vmf;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import java.util.*;

public class vmf49_inputtoresult extends com.altova.TraceProvider 
{

	
	static class Main implements IEnumerable
	{
		java.lang.String var1_input;
	
		public Main(java.lang.String var1_input)
		{
			this.var1_input = var1_input;
		}

		public IEnumerator enumerator() {return new MFEmptySequence().enumerator();}
				
	}





	public static IEnumerable create(java.lang.String var1_input)
	{
		if (hash == null) init();
		Object o = hash.get(var1_input);
		if (o != null)
			return new MFSingletonSequence(o);
		else
			return new MFEmptySequence();

	}
	
	private static java.util.HashMap hash = null;

	private synchronized static void init()
	{
		hash = new java.util.HashMap();
		hash.put(com.altova.CoreTypes.box("Chilled Water"), com.altova.CoreTypes.box("District chilled water"));
		hash.put(com.altova.CoreTypes.box("Hot Water"), com.altova.CoreTypes.box("District hot water"));
		hash.put(com.altova.CoreTypes.box("Fuel Oil"), com.altova.CoreTypes.box("Fuel oil"));
		hash.put(com.altova.CoreTypes.box("Propane"), com.altova.CoreTypes.box("Propane"));
		hash.put(com.altova.CoreTypes.box("Steam"), com.altova.CoreTypes.box("District steam"));
		hash.put(com.altova.CoreTypes.box("Other"), com.altova.CoreTypes.box("Other"));
	}

	public static com.altova.mapforce.IEnumerable eval(java.lang.String var1_input) throws java.lang.Exception
	{

		return create(var1_input);
	
	}

}
